### ISSUE TITLE
Typo for property offset.retention.minutes gen.conf.tmpl.sh

### ISSUE THREAD

**Issue by tmelhiser** [rawmind0/rancher-kafka#5]
Typo bug in gen.conf.tmpl.sh:

offset needs to plural: offsets

***wrong***
offset.retention.minutes=${KAFKA_OFFSET_RETENTION_MINUTES}

***right***
offsets.retention.minutes=${KAFKA_OFFSET_RETENTION_MINUTES}

**Comment by rawmind0** [comment]
Thanks @tmelhiser ... 

Fixed at release rawmind0/rancher-kafka:0.11.0.0-2
